version: 2
jobs:
  html-docs:
    docker:
      - image: centos:7.6.1810
    steps:
      - checkout
      - run:
          name: "Install Doxygen and dependencies"
          command: yum install -y make doxygen graphviz
      - run:
          name: "Build docs"
          command: make doc
      - persist_to_workspace:
          root: doc
          paths: output
      - store_artifacts:
          path: doc/output
      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="${CIRCLE_BUILD_URL}/artifacts/${CIRCLE_NODE_INDEX}/${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}/doc/output/index.html"; echo $DOCS_URL
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "87:bc:05:35:3a:b8:4c:99:5f:89:ea:fa:6f:78:22:eb"
      - checkout
      - attach_workspace:
          at: doc
      - run:
          name: Disable jekyll builds
          command: touch doc/output/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "lynx@magao-x.org"
            git config user.name "Lynx the Cat"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Update built docs" --dist doc/output/
  build_centos:
    docker:
      - image: centos:7.6.1810
    steps:
      - checkout
      - run:
          name: Add sudo
          command: 'yum install -y sudo'
      - run:
          name: Checksum provisioning scripts
          command: 'find ~/project/setup/ -type f -exec md5sum {} \; | sort -k 2 > ~/project/provisioning_scripts_checksums.txt'
      - restore_cache:
          keys:
            - dependencies-cache-v1-{{ checksum "provisioning_scripts_checksums.txt" }}
      - run:
          name: Auto-provision
          command: 'bash -l ~/project/setup/provision.sh'
      - save_cache:
          key: dependencies-cache-v1-{{ checksum "provisioning_scripts_checksums.txt" }}
          paths:
            - /opt/MagAOX/vendor
            - /opt/MagAOX/.cache
      - run:
          name: Install MagAO-X
          command: 'bash -l ~/project/setup/steps/install_MagAOX.sh ci'
  build_ubuntu:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Add sudo
          command: 'apt-get update && apt-get install -y sudo'
      - run:
          name: Checksum provisioning scripts
          command: 'find ~/project/setup/ -type f -exec md5sum {} \; | sort -k 2 > ~/project/provisioning_scripts_checksums.txt'
      - restore_cache:
          keys:
            - dependencies-cache-ubuntu-{{ checksum "provisioning_scripts_checksums.txt" }}
      - run:
          name: Auto-provision
          command: 'bash -l ~/project/setup/provision.sh'
      - save_cache:
          key: dependencies-cache-ubuntu-{{ checksum "provisioning_scripts_checksums.txt" }}
          paths:
            - /opt/MagAOX/vendor
            - /opt/MagAOX/.cache
      - run:
          name: Install MagAO-X
          command: 'bash -l ~/project/setup/steps/install_MagAOX.sh ci'
workflows:
  version: 2
  ubuntu:
    jobs:
      - build_ubuntu
  centos:
    jobs:
      - build_centos
  build_and_upload:
    jobs:
      - html-docs
      - docs-deploy:
          requires:
            - html-docs
          filters:
            branches:
              only: master
