name: Build C++ Doxygen documentation
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y doxygen
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd ${{ github.workspace }} && doxygen doc/config/Doxyfile.libMagAOX
